<?php
    if (defined('STDIN')) {
        $options=getopt("D:s:d:t::");
        if (!($options)) {
            echo "Usage:\n";
            echo "    php-cli __DBADMINcreateDatabase__.php -D dbconfigfile -s schemafile.sql -d datafile.sql -t[=YES]\n";
            echo "    -D xxx part of database config.xxx.inc.php filename, astfdb_test and astfdb_prod are the 2 options\n";
            echo "    -s schemafile generated by using mysqldump --no-data --skip-triggers\n";
            echo "    -d datafile generated by using mysqldump --no-create-info --skip-triggers\n";
            echo "    -t without anything following to drop all triggers for this database\n";
            echo "    -t=YES to add all triggers from within the script (RECOMMENDED)\n";
            echo "    -t file containing procs/triggers ...mysqldump --no-create-info --no-create-db --no-data --routines --skip-opt (NOT RECOMMENDED)\n";
            echo "why? if triggers are added before data load, they will start firing\n";
            exit;
        }

        echo "Running from command line\n";
        echo "Options:";
        var_dump($options);

        if (array_key_exists("t",$options) && $options["t"] === false) {
            if ($options["s"] || $options["d"]) {
                echo "The -t flag without any value must be run only with -D to drop all triggers\n";
                exit;
            }
            if ($options["D"] === false) {
                echo "The -t flag without any value must specify the -D option\n";
                exit;
            }
        }

        require('config.'.$options["D"].'.inc.php');
        $strCommand = sprintf("mysql -h %s -u %s -p%s %s",$arrCredentials["DBhost"],$arrCredentials["DBuser"],$arrCredentials["DBpass"],$arrCredentials["DBname"]);
        if($options["s"]) {
            echo "Importing schema from file\n";
            exec($strCommand." < ".$options["s"]);
        } else {
            echo "Schema not touched\n";
        }

        if($options["d"]) {
            echo "Importing data from file\n";
            exec($strCommand." < ".$options["d"]);
        } else {
            echo "No data imported\n";
        }

        if(array_key_exists("t",$options)) {
            if($options["t"] === false) {
                echo "Dropping triggers for this database\n";
                addTriggersProcs($arrCredentials, true);
            } else if($options["t"] == 'YES') {
                echo "Adding triggers from this script\n";
                addTriggersProcs($arrCredentials);
            } else {
                echo "Importing procs/triggers from file\n";
                exec($strCommand." < ".$options["t"]);
            }
        } else {
            echo "No triggers touched\n";
        }
    }

function addTriggersProcs($arrCredentials, $blnDropOnly=false) {
    echo "Connect\n";
    $hndDatabase=mysql_connect($arrCredentials['DBhost'], $arrCredentials['DBuser'], $arrCredentials['DBpass']);
    if ($hndDatabase) {
        mysql_select_db($arrCredentials['DBname'],$hndDatabase);
    } // end if $hndDatabase
    else {
        echo (mysql_error());
        mysql_close($hndDatabase);
    } // end else $hndDatabase

    // Cannot do drop and create using 1 mysql_query from php, learnt after syntax error on line 2 messages
    mysql_query("DROP PROCEDURE IF EXISTS `doLogChanges`;");
    echo mysql_error();
    $strSql = "CREATE PROCEDURE doLogChanges(
                        strTableName VARCHAR(64),
                        intRowID INT,
                        strDescription VARCHAR(128)
                )
                BEGIN
                    INSERT INTO tblHistory (TableName, PrimaryKeyID, ParticipantID, DateTimeModified, Description) VALUES (
                        strTableName,
                        intRowID,
                        @DataEntryPersonID,
                        NOW(),
                        strDescription
                    );
                END;";
    mysql_query($strSql);
    echo mysql_error();

    $arrNoHistory = array("tblHistory","tblIpAddresses","tblMapWikiIds");
    $strSql = "SELECT table_name FROM information_schema.tables WHERE table_schema='".$arrCredentials['DBname']."'";
    $strSql .= " AND table_name NOT LIKE 'tblCombo%'";
    $strSql .= " AND table_name NOT IN ('".implode("','",$arrNoHistory)."')";
    $objResult = mysql_query($strSql);
    while ($row = mysql_fetch_assoc($objResult)) {
        $strTable = $row['table_name'];
        $objResult1 = mysql_query("SHOW COLUMNS FROM ".$strTable);
        $strDescription = "";
        while ($column = mysql_fetch_assoc($objResult1)) {
            if ($column['Field'] != 'ID') {
                $strField = $column['Field'];
                $strDescription .= "IF (OLD.{$strField} <=> NEW.{$strField}, NULL, CONCAT('{$strField}=',OLD.{$strField},':',NEW.{$strField})),\n";
            }
        }
        $strDescription = substr($strDescription,0,-2);
        $strSql = "DROP TRIGGER IF EXISTS `trgAfterUpdate{$strTable}`;";
        mysql_query($strSql);
        echo mysql_error();
        $strSql = "CREATE TRIGGER `trgAfterUpdate{$strTable}` AFTER UPDATE ON `{$strTable}` FOR EACH ROW
                        CALL doLogChanges('{$strTable}', NEW.ID, CONCAT_WS(',',
                        'UPDATE',{$strDescription}));";
        if (!$blnDropOnly) mysql_query($strSql);
        echo mysql_error();

        $strSql = "DROP TRIGGER IF EXISTS `trgAfterInsert{$strTable}`;";
        mysql_query($strSql);
        echo mysql_error();
        $strSql = "CREATE TRIGGER trgAfterInsert{$strTable} AFTER INSERT ON {$strTable} FOR EACH ROW
                        CALL doLogChanges('{$strTable}', NEW.id, 'INSERT');";

        if (!$blnDropOnly) mysql_query($strSql);
        echo mysql_error();
    }

    mysql_close($hndDatabase);
}
?>
